version: '3.8'
services:
  bot:
    build: .
    ports:
      - 8000:8000
    env_file:
      - .env
    environment:
      TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      MONGODB_URI: "mongodb://db:27017"
    depends_on:
      - db
  db:
    command: mongod
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - mongodb_data:/data/db
volumes:
  mongodb_data:
